# Generated by Django 5.2.1 on 2025-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
