# Generated by Django 5.2.1 on 2025-06-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
