# Generated by Django 5.2.1 on 2025-06-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'verbose_name': 'Comunicados', 'verbose_name_plural': 'Comunicado'},
        ),
    ]
